#include <sdkddkver.h>
#define DEFINE_NS_ONLY
#include "../Tomato.Media.Effect.Shared/common.h"

import "oaidl.idl";
import "ocidl.idl";
import "inspectable.idl";
import "Windows.Media.idl";

DEFINE_NS_MEDIA_EFFECT

[uuid(DFC6F70B-BD21-47B9-ACA1-951F1C0E1B42)]
[version(1.0)]
interface IEqualizerEffectProps : IInspectable
{
	HRESULT AddOrUpdateFilter([in]FLOAT frequency, [in]FLOAT bandWidth, [in]FLOAT gain);
	HRESULT RemoveFilter([in]FLOAT frequency);
};

[version(NTDDI_WIN8)]
[activatable(NTDDI_WIN8)]
[marshaling_behavior(agile)]
runtimeclass EqualizerEffectTransform
{
	[default] interface Windows.Media.IMediaExtension;
interface IEqualizerEffectProps;
}

END_NS_MEDIA_EFFECT